name:                websocket-inspector
version:             0.1.0.0
github:              "ecthiender/websocket-inspector"
license:             BSD3
author:              "Anon Ray"
maintainer:          "rayanon004@gmail.com"
copyright:           "Anon Ray"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/websocket-inspector#readme>

dependencies:
- base >= 4.7 && < 5
- mtl # maybe not needed
- text
- bytestring
- brick
- vty
- websockets
- wuss
- time
- optparse-generic
- microlens
- microlens-th
- text-zipper
- vector
- network-uri

library:
  source-dirs: src
  ghc-options: -O2

executables:
  websocket-inspector:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websocket-inspector

tests:
  websocket-inspector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websocket-inspector
